module.exports = {
  lang_title: '🌐 اختيار اللغة',
  lang_description: 'اختر اللغة التي تريد ان يرد بها البوت على رسائلك',
  lang_placeholder: '🌍 اختر لغتك',
  lang_changed: '✅ تم اختيار اللغة: **العربية** 🇪🇬',
  lang_current: 'اللغة الحالية',

  help_title: '🔥 لوحة أوامر V9 Bot',
  help_desc: '**الاجمالي:** {0} امر\nاختر فئة من القائمة بالاسفل لاستعراض اوامرها',
  help_placeholder: '📚 اختر فئة الاوامر',
  help_home: '🏠 الصفحة الرئيسية',
  help_home_desc: 'العودة للقائمة الرئيسية',
  help_commands_count: '{0} امر',
  help_select_category: '**{0}** امر — اخترها من القائمة',

  error_title: '❌ خطا',
  error_generic: 'حدث خطا غير متوقع، حاول مرة اخرى',
  no_permission: '⛔ غير مصرح',
  no_permission_bot: '⚠️ صلاحيات البوت',
  cooldown_wait: '⏳ انتظر {0} ثانية لاستخدام هذا الامر',
  unknown_interaction: 'تفاعل غير معروف',
  unknown_modal: 'نافذة غير معروفة',

  cat_info: 'ℹ️ معلومات',
  cat_moderation: '🛠️ إدارة',
  cat_config: '⚙️ إعدادات',
  cat_protection: '🛡️ حماية',
  cat_tickets: '🎫 تذاكر',
  cat_owner: '👑 مطور',

  // AFK
  afk_set_desc: 'تفعيل وضع الافك مع سبب',
  afk_reason: 'السبب (اختياري)',
  afk_off_desc: 'ازالة وضع الافك',
  afk_not_active: '❌ لست في وضع افك',
  afk_use_set: 'استخدم /afk set لتحديد حالة الافك',
  afk_removed: '✅ ازيلت حالة الافك',
  afk_welcome_back: 'اهلا بعودتك! 🎉',
  afk_no_reason: 'لم يحدد سبب',
  afk_active_title: '💤 انت في وضع الافك الان',
  afk_active_desc: '**السبب:** {0}\nعندما يعمّلك احدهم منشن سيعلمهم البوت ويوجههم إليك',
  afk_removed_title: '💤 ازيلت حالة الافك',
  afk_mention_title: '💤 وضع الافك',
  afk_mention_is: 'في وضع الافك حاليا',
  afk_mention_reason: 'السبب',
  afk_mention_since: 'منذ',
  afk_mention_goto: 'يرجى القدوم إليه في',

  // Temp Voice
  tv_desc: 'الرومات الصوتية المؤقتة',
  tv_setup_desc: 'تفعيل النظام',
  tv_channel: 'روم الانشاء (صوتي)',
  tv_category: 'كاتيجوري الرومات الجديدة (اختياري — يرث من روم الانشاء)',
  tv_limit: 'الحد الاقصى للاعضاء (0 = بدون حد)',
  tv_disable_desc: 'ايقاف النظام',
  tv_status_desc: 'عرض حالة النظام',
  tv_must_voice: 'يجب اختيار روم صوتي',
  tv_create_failed: '❌ فشل انشاء روم الانشاء',
  tv_auto_channel_name: '🔊 اضغط هنا',
  tv_enabled_title: '✅ تم التفعيل',
  tv_enabled_desc: 'تم تفعيل الرومات الصوتية المؤقتة\n**روم الانشاء:** {0}\n**الكاتيجوري:** {1}\n**الحد الاقصى:** {2}\n\n💡 ادخل الروم وهينشأ لك روم خاص باسمك',
  tv_disabled_title: '⏹️ تم الايقاف',
  tv_disabled_desc: 'تم ايقاف الرومات المؤقتة',
  tv_status_title: '📊 حالة الرومات المؤقتة',
  tv_status: 'الحالة',
  tv_enabled: 'مفعل',
  tv_disabled: 'متوقف',
  tv_create_channel: 'روم الانشاء',
  tv_cat: 'الكاتيجوري',
  tv_inherits: 'يرث من روم الانشاء',
  tv_user_limit: 'الحد الاقصى',
  tv_unlimited: 'بدون حد',

  // Suggestions
  sug_setup_desc: 'تفعيل النظام واختيار روم الاقتراحات',
  sug_channel: 'روم الاقتراحات',
  sug_disable_desc: 'ايقاف النظام',
  sug_status_desc: 'عرض حالة النظام',
  sug_enabled_title: '✅ تم التفعيل',
  sug_enabled_desc: 'تم تفعيل نظام الاقتراحات\n**الروم:** {0}\n\nستتحول رسائل الروم لايمبيدات اقتراح مع زري ✅ و ❌ للتصويت',
  sug_disabled_title: '⏹️ تم الايقاف',
  sug_disabled_desc: 'تم ايقاف نظام الاقتراحات',
  sug_status_title: '📊 حالة نظام الاقتراحات',
  sug_status: 'الحالة',
  sug_enabled_state: 'مفعل',
  sug_disabled_state: 'متوقف',
  sug_channel_label: 'الروم',
  sug_count: 'عدد الاقتراحات',
  sug_not_found: 'الاقتراح غير موجود',
  sug_voted_title: '✅ تم التصويت',
  sug_voted_desc: 'شكرا لتصويتك! اضغط مرة اخرى لالغاء صوتك',
  sug_new_title: '💡 اقتراح جديد',
  sug_no_content: '_لا يوجد محتوى_',
  sug_upvotes: '✅ مؤيد',
  sug_downvotes: '❌ معارض',
  sug_score: '📊 النتيجة',
  sug_footer: 'اقتراح #{0}',
  sug_send_failed: 'تعذر ارسال الاقتراح، اعد المحاولة',

  // Referral
  ref_code_desc: 'عرض كود الاحالة الخاص بك',
  ref_use_desc: 'تفعيل كود احالة (للاعضاء الجدد)',
  ref_code_label: 'الكود',
  ref_setup_desc: 'تفعيل النظام واختيار قناة السجل (ادارة)',
  ref_log_channel: 'قناة سجل الاحالات',
  ref_reward_desc: 'رول المكافأة الذي يحصل عليه المدعو (ادارة)',
  ref_reward_role: 'رول المكافأة',
  ref_disable_desc: 'ايقاف النظام (ادارة)',
  ref_status_desc: 'عرض حالة النظام',
  ref_code_title: '🎟️ كود الاحالة الخاص بك',
  ref_code_desc_text: '**كودك:** `{0}`\n**عدد احالاتك:** {1}\n\nشارك الكود مع الاعضاء الجدد ليحصل كل منكما على المكافأة 🎁',
  ref_unauthorized: 'هذا الامر لادارة السيرفر',
  ref_enabled_title: '✅ تم التفعيل',
  ref_enabled_desc: 'تم تفعيل نظام الاحالات\n**قناة السجل:** {0}',
  ref_done_title: '✅ تم',
  ref_done_desc: 'رول المكافأة: {0}',
  ref_disabled_title: '⏹️ تم الايقاف',
  ref_disabled_desc: 'تم ايقاف نظام الاحالات',
  ref_status_title: '📊 حالة نظام الاحالات',
  ref_status: 'الحالة',
  ref_enabled_state: 'مفعل',
  ref_disabled_state: 'متوقف',
  ref_log_label: 'قناة السجل',
  ref_reward_label: 'رول المكافأة',
  ref_invalid_code: 'اكتب كود احالة صحيح',
  ref_unknown_code: 'هذا الكود غير موجود في النظام',
  ref_own_code: 'لا يمكنك استخدام كودك الخاص',
  ref_time_expired: 'يمكنك تفعيل كود الاحالة خلال 24 ساعة من الانضمام',
  ref_already_used: 'استخدمت كود احالة من قبل',
  ref_owner_missing: 'صاحب هذا الكود غير موجود في السيرفر',
  ref_new_title: '🤝 احالة جديدة',
  ref_new_desc: '**{0}** ({1}) انضم بفضل **{2}**\n**الكود:** `{3}`\n**اجمالي احالات {4}:** {5}',
  ref_activated_title: '🎉 تم تفعيل الاحالة',
  ref_activated_desc: 'اهلا بك! تم تسجيل احالتك بواسطة **{0}** 🎁',

  // Reload
  reload_synced: 'تسجيل الاوامر:',
  reload_sync_failed: 'فشل تسجيل الاوامر:',
  reload_title: '🔄 تم اعادة التحميل',
  reload_desc: 'تم تحميل **{0}** امر',

  // Invite tracking
  invite_stats_title: '📊 إحصائيات الانفايتات',
  invite_total: 'اجمالي الدعوات',
  invite_normal: 'العادية',
  invite_fake: 'الوهمية',
  invite_lb_title: '🏆 لوحة ترتيب الانفايتات',
  invite_no_data: 'لا توجد بيانات انفايتات بعد',
  invite_joins: 'عضو',
  invite_reset_title: '🔄 تم اعادة الضبط',
  invite_reset_user: 'تم اعادة ضبط انفايتات **{0}** — **{1}** دعوة',
  invite_reset_all: 'تم اعادة ضبط كل الانفايتات — **{0}** دعوة',

  // DM Shop
  shop_dm_title: '📌 أوامر المتجر في الخاص',
  shop_dm_desc: '**في الخاص، المتاح لك فقط أوامر الشراء والاشتراك:**\n\n💡 عندك سيريال؟ فعّله بامر `/redeem`.',

  // Server Log
  sl_cleared: '✅ تم مسح السجل',
  sl_no_events: 'لا توجد أحداث مسجلة بعد',
  sl_stats: 'الإحصائيات',
  sl_roles: 'رولات',
  sl_channels: 'قنوات',
  sl_categories: 'كاتيجوريات',
  sl_more: 'حدث اضافي',
  sl_btn_all: 'الكل',
  sl_btn_roles: 'رولات',
  sl_btn_channels: 'قنوات',
  sl_btn_categories: 'كاتيجوريات',
};
