module.exports = {
  lang_title: '🌐 Choose Language',
  lang_description: 'Choose the language the bot should reply to you in',
  lang_placeholder: '🌍 Select your language',
  lang_changed: '✅ Language set to: **English** 🇬🇧',
  lang_current: 'Current language',

  help_title: '🔥 V9 Bot Command Center',
  help_desc: '**Total:** {0} commands\nSelect a category below to browse its commands',
  help_placeholder: '📚 Choose a command category',
  help_home: '🏠 Home Page',
  help_home_desc: 'Back to the main menu',
  help_commands_count: '{0} commands',
  help_select_category: '**{0}** commands — select from the menu',

  error_title: '❌ Error',
  error_generic: 'An unexpected error occurred, try again',
  no_permission: '⛔ Not allowed',
  no_permission_bot: '⚠️ Bot permissions',
  cooldown_wait: '⏳ Wait {0} seconds before using this command',
  unknown_interaction: 'Unknown interaction',
  unknown_modal: 'Unknown modal',

  cat_info: 'ℹ️ Info',
  cat_moderation: '🛠️ Moderation',
  cat_config: '⚙️ Settings',
  cat_protection: '🛡️ Protection',
  cat_tickets: '🎫 Tickets',
  cat_owner: '👑 Owner',

  // AFK
  afk_set_desc: 'Set AFK with a reason',
  afk_reason: 'Reason (optional)',
  afk_off_desc: 'Remove AFK status',
  afk_not_active: '❌ You are not AFK',
  afk_use_set: 'Use /afk set to set your AFK status',
  afk_removed: '✅ AFK removed',
  afk_welcome_back: 'Welcome back! 🎉',
  afk_no_reason: 'No reason set',
  afk_active_title: '💤 You are now AFK',
  afk_active_desc: '**Reason:** {0}\nThe bot will notify and guide others when they mention you',
  afk_removed_title: '💤 AFK removed',
  afk_mention_title: '💤 AFK Status',
  afk_mention_is: 'is currently AFK',
  afk_mention_reason: 'Reason',
  afk_mention_since: 'Since',
  afk_mention_goto: 'Please come to him in',

  // Temp Voice
  tv_desc: 'Temporary voice rooms',
  tv_setup_desc: 'Enable the system',
  tv_channel: 'Create channel (voice)',
  tv_category: 'Category for new rooms (optional — inherits from create channel)',
  tv_limit: 'Max members (0 = unlimited)',
  tv_disable_desc: 'Disable the system',
  tv_status_desc: 'Show system status',
  tv_must_voice: 'You must select a voice channel',
  tv_create_failed: '❌ Failed to create the channel',
  tv_auto_channel_name: '🔊 Click Here',
  tv_enabled_title: '✅ Enabled',
  tv_enabled_desc: 'Temporary voice rooms enabled\n**Create channel:** {0}\n**Category:** {1}\n**Max members:** {2}\n\n💡 Join the channel and a private room will be created for you',
  tv_disabled_title: '⏹️ Disabled',
  tv_disabled_desc: 'Temporary voice disabled',
  tv_status_title: '📊 Temporary voice status',
  tv_status: 'Status',
  tv_enabled: 'Enabled',
  tv_disabled: 'Disabled',
  tv_create_channel: 'Create channel',
  tv_cat: 'Category',
  tv_inherits: 'Inherits from create channel',
  tv_user_limit: 'User limit',
  tv_unlimited: 'Unlimited',

  // Suggestions
  sug_setup_desc: 'Enable the system and set the suggestions channel',
  sug_channel: 'Suggestions channel',
  sug_disable_desc: 'Disable the system',
  sug_status_desc: 'Show system status',
  sug_enabled_title: '✅ Enabled',
  sug_enabled_desc: 'Suggestion system enabled\n**Channel:** {0}\n\nMessages will be converted to suggestion embeds with ✅ and ❌ vote buttons',
  sug_disabled_title: '⏹️ Disabled',
  sug_disabled_desc: 'Suggestion system disabled',
  sug_status_title: '📊 Suggestion system status',
  sug_status: 'Status',
  sug_enabled_state: 'Enabled',
  sug_disabled_state: 'Disabled',
  sug_channel_label: 'Channel',
  sug_count: 'Suggestions',
  sug_not_found: 'Suggestion not found',
  sug_voted_title: '✅ Voted',
  sug_voted_desc: 'Thanks for voting! Click again to remove your vote',
  sug_new_title: '💡 New Suggestion',
  sug_no_content: '_No content_',
  sug_upvotes: '✅ Upvotes',
  sug_downvotes: '❌ Downvotes',
  sug_score: '📊 Score',
  sug_footer: 'Suggestion #{0}',
  sug_send_failed: 'Could not post your suggestion, try again',

  // Referral
  ref_code_desc: 'Show your referral code',
  ref_use_desc: 'Use a referral code (new members)',
  ref_code_label: 'Code',
  ref_setup_desc: 'Enable the system and set the log channel (admin)',
  ref_log_channel: 'Referral log channel',
  ref_reward_desc: 'Reward role for referrers (admin)',
  ref_reward_role: 'Reward role',
  ref_disable_desc: 'Disable the system (admin)',
  ref_status_desc: 'Show system status',
  ref_code_title: '🎟️ Your referral code',
  ref_code_desc_text: '**Your code:** `{0}`\n**Referrals:** {1}\n\nShare your code with new members to both earn rewards 🎁',
  ref_unauthorized: 'This command is for server staff',
  ref_enabled_title: '✅ Enabled',
  ref_enabled_desc: 'Referral system enabled\n**Log channel:** {0}',
  ref_done_title: '✅ Done',
  ref_done_desc: 'Reward role: {0}',
  ref_disabled_title: '⏹️ Disabled',
  ref_disabled_desc: 'Referral system disabled',
  ref_status_title: '📊 Referral system status',
  ref_status: 'Status',
  ref_enabled_state: 'Enabled',
  ref_disabled_state: 'Disabled',
  ref_log_label: 'Log channel',
  ref_reward_label: 'Reward role',
  ref_invalid_code: 'Enter a valid referral code',
  ref_unknown_code: 'This code does not exist in the system',
  ref_own_code: 'You cannot use your own code',
  ref_time_expired: 'Referral codes can only be used within 24 hours of joining',
  ref_already_used: 'You have already used a referral code',
  ref_owner_missing: 'The owner of this code is not in this server',
  ref_new_title: '🤝 New referral',
  ref_new_desc: '**{0}** ({1}) joined thanks to **{2}**\n**Code:** `{3}`\n**Total referrals by {4}:** {5}',
  ref_activated_title: '🎉 Referral activated',
  ref_activated_desc: 'Welcome! Your referral by **{0}** has been recorded 🎁',

  // Reload
  reload_synced: 'Commands synced:',
  reload_sync_failed: 'Command sync failed:',
  reload_title: '🔄 Reloaded',
  reload_desc: 'Loaded **{0}** commands',

  // Invite tracking
  invite_stats_title: '📊 Invite Stats',
  invite_total: 'Total invites',
  invite_normal: 'Normal',
  invite_fake: 'Fake',
  invite_lb_title: '🏆 Invite Leaderboard',
  invite_no_data: 'No invite data yet',
  invite_joins: 'joins',
  invite_reset_title: '🔄 Reset Complete',
  invite_reset_user: 'Reset invites for **{0}** — **{1}** invites',
  invite_reset_all: 'Reset all invites — **{0}** invites',

  // DM Shop
  shop_dm_title: '📌 Shop Commands (DM)',
  shop_dm_desc: '**In DMs, only purchase/subscription commands are available:**\n\n💡 Have a serial? Activate it with `/redeem`.',

  // Server Log
  sl_cleared: '✅ Log cleared',
  sl_no_events: 'No events recorded yet',
  sl_stats: 'Stats',
  sl_roles: 'Roles',
  sl_channels: 'Channels',
  sl_categories: 'Categories',
  sl_more: 'more events',
  sl_btn_all: 'All',
  sl_btn_roles: 'Roles',
  sl_btn_channels: 'Channels',
  sl_btn_categories: 'Categories',
};
